@echo off


C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
C:\Python312\pythonw.exe .\__main__.py
